package alviano.kotlin.restful.error

class UnauthorizedException: Exception() {
}